package com.exam.system.service;

import com.exam.system.dto.StudentDTO;
import com.exam.system.dto.TeacherDTO;
import com.exam.system.dto.SubjectDTO;
import com.exam.system.dto.GradeDTO;
import com.exam.system.model.Student;
import com.exam.system.model.Teacher;
import com.exam.system.model.Subject;
import com.exam.system.model.Grade;
import com.exam.system.model.User;
import com.exam.system.repository.StudentRepository;
import com.exam.system.repository.TeacherRepository;
import com.exam.system.repository.SubjectRepository;
import com.exam.system.repository.GradeRepository;
import com.exam.system.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.stream.Collectors;

@Service
public class AdminService {

    @Autowired
    private UserRepository userRepository;
    
    @Autowired
    private StudentRepository studentRepository;
    
    @Autowired
    private TeacherRepository teacherRepository;
    
    @Autowired
    private SubjectRepository subjectRepository;
    
    @Autowired
    private GradeRepository gradeRepository;
    
    @Autowired
    private PasswordEncoder passwordEncoder;

    public StudentDTO createStudent(StudentDTO studentDTO) {
        // Create and populate the user entity
        User user = new User();
        // User ID will be auto-generated by MyBatisPlus
        user.setUsername(studentDTO.getStudentId());
        user.setEmail(studentDTO.getEmail()); // Use email from DTO
        user.setRole(User.Role.STUDENT);
        user.setFirstName(studentDTO.getFirstName());
        user.setLastName(studentDTO.getLastName());
        user.setIsActive(true);
        
        // Set a default password that needs to be changed
        user.setPasswordHash(passwordEncoder.encode("defaultPassword123"));
        
        // Insert the user first
        userRepository.insert(user);
        
        // Create and populate the student entity
        Student student = new Student();
        student.setStudentId(studentDTO.getStudentId());
        student.setGradeId(studentDTO.getGradeId());
        student.setClassId(studentDTO.getClassId());
        student.setParentId(studentDTO.getParentId());
        student.setUserId(user.getId()); // Link to the created user
        
        // Insert the student
        studentRepository.insert(student);

        // Convert back to DTO and return
        return convertToDTO(student);
    }

    public TeacherDTO createTeacher(TeacherDTO teacherDTO) {
        // Create and populate the user entity
        User user = new User();
        // User ID will be auto-generated by MyBatisPlus
        user.setUsername(teacherDTO.getEmployeeId());
        user.setEmail(teacherDTO.getEmail());
        user.setRole(User.Role.TEACHER);
        user.setFirstName(teacherDTO.getFirstName());
        user.setLastName(teacherDTO.getLastName());
        user.setIsActive(true);
        
        // Set a default password that needs to be changed
        user.setPasswordHash(passwordEncoder.encode("defaultPassword123"));
        
        // Insert the user first
        userRepository.insert(user);
        
        // Create and populate the teacher entity
        Teacher teacher = new Teacher();
        teacher.setEmployeeId(teacherDTO.getEmployeeId());
        teacher.setDepartment(teacherDTO.getDepartment());
        teacher.setHireDate(teacherDTO.getHireDate());
        teacher.setUserId(user.getId()); // Link to the created user
        
        // Insert the teacher
        teacherRepository.insert(teacher);

        // Convert back to DTO and return
        return convertToTeacherDTO(teacher);
    }

    public SubjectDTO createSubject(SubjectDTO subjectDTO) {
        // Create and populate the subject entity
        Subject subject = new Subject();
        subject.setName(subjectDTO.getName());
        subject.setCode(subjectDTO.getCode());
        subject.setDescription(subjectDTO.getDescription());
        subject.setIsActive(true);
        
        // Insert the subject
        subjectRepository.insert(subject);

        // Convert back to DTO and return
        return convertToSubjectDTO(subject);
    }

    public GradeDTO createGrade(GradeDTO gradeDTO) {
        // Create and populate the grade entity
        Grade grade = new Grade();
        grade.setName(gradeDTO.getName());
        grade.setCode(gradeDTO.getCode());
        grade.setDescription(gradeDTO.getDescription());
        grade.setMinAge(gradeDTO.getMinAge());
        grade.setMaxAge(gradeDTO.getMaxAge());
        grade.setIsActive(true);
        
        // Insert the grade
        gradeRepository.insert(grade);

        // Convert back to DTO and return
        return convertToGradeDTO(grade);
    }

    private StudentDTO convertToDTO(Student student) {
        if (student == null) {
            return null;
        }
        
        StudentDTO dto = new StudentDTO();
        dto.setId(student.getId());
        dto.setStudentId(student.getStudentId());
        dto.setGradeId(student.getGradeId());
        dto.setClassId(student.getClassId());
        dto.setParentId(student.getParentId());
        dto.setUserId(student.getUserId());
        
        return dto;
    }

    private TeacherDTO convertToTeacherDTO(Teacher teacher) {
        if (teacher == null) {
            return null;
        }
        
        TeacherDTO dto = new TeacherDTO();
        dto.setId(teacher.getId());
        dto.setEmployeeId(teacher.getEmployeeId());
        dto.setDepartment(teacher.getDepartment());
        dto.setHireDate(teacher.getHireDate());
        dto.setUserId(teacher.getUserId());
        
        return dto;
    }

    private SubjectDTO convertToSubjectDTO(Subject subject) {
        if (subject == null) {
            return null;
        }
        
        SubjectDTO dto = new SubjectDTO();
        dto.setId(subject.getId());
        dto.setName(subject.getName());
        dto.setCode(subject.getCode());
        dto.setDescription(subject.getDescription());
        dto.setIsActive(subject.getIsActive());
        
        return dto;
    }

    private GradeDTO convertToGradeDTO(Grade grade) {
        if (grade == null) {
            return null;
        }
        
        GradeDTO dto = new GradeDTO();
        dto.setId(grade.getId());
        dto.setName(grade.getName());
        dto.setCode(grade.getCode());
        dto.setDescription(grade.getDescription());
        dto.setMinAge(grade.getMinAge());
        dto.setMaxAge(grade.getMaxAge());
        dto.setIsActive(grade.getIsActive());
        
        return dto;
    }
}