package com.exam.system.service;

import com.exam.system.model.ClassEnrollment;
import com.exam.system.repository.ClassEnrollmentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;

@Service
public class StudentTransferService {

    @Autowired
    private ClassEnrollmentRepository classEnrollmentRepository;

    public boolean transferStudent(Long studentId, Long newClassId) {
        // Find the current enrollment
        ClassEnrollment currentEnrollment = classEnrollmentRepository
            .findByStudentIdAndStatus(studentId, com.exam.system.model.ClassEnrollment.Status.ACTIVE);
            
        if (currentEnrollment != null) {
            // Update the current enrollment to TRANSFERRED status
            currentEnrollment.setStatus(com.exam.system.model.ClassEnrollment.Status.TRANSFERRED);
            currentEnrollment.setTransferDate(LocalDateTime.now());
            currentEnrollment.setPreviousClassId(currentEnrollment.getClassId());
            classEnrollmentRepository.updateById(currentEnrollment);
            
            // Create a new enrollment for the new class
            ClassEnrollment newEnrollment = new ClassEnrollment();
            // ID will be auto-generated by MyBatisPlus
            newEnrollment.setStudentId(studentId);
            newEnrollment.setClassId(newClassId);
            newEnrollment.setStatus(com.exam.system.model.ClassEnrollment.Status.ACTIVE);
            
            classEnrollmentRepository.insert(newEnrollment);
            
            return true;
        }
        
        return false;
    }
}