package com.exam.system.service;

import com.exam.system.dto.StudentResponseDTO;
import com.exam.system.model.Question;
import com.exam.system.model.StudentResponse;
import com.exam.system.model.Test;
import com.exam.system.model.TestAssignment;
import com.exam.system.repository.QuestionRepository;
import com.exam.system.repository.StudentResponseElasticsearchRepository;
import com.exam.system.repository.StudentResponseRepository;
import com.exam.system.repository.TestRepository;
import com.exam.system.repository.TestAssignmentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

@Service
public class TestTakingService {

    @Autowired
    private StudentResponseRepository studentResponseRepository;
    
    @Autowired
    private TestRepository testRepository;
    
    @Autowired
    private TestAssignmentRepository testAssignmentRepository;
    
    @Autowired
    private QuestionRepository questionRepository;
    
    @Autowired(required = false)
    private StudentResponseElasticsearchRepository studentResponseElasticsearchRepository;

    public List<StudentResponseDTO> submitTest(Long testId, Long studentId, List<StudentResponseDTO> responses) {
        // Verify that the test exists and is assigned to the student
        Test test = testRepository.selectById(testId);
        if (test == null) {
            throw new IllegalArgumentException("Test not found");
        }
        
        // Check if the test is assigned to the student
        TestAssignment testAssignment = testAssignmentRepository.findByTestIdAndStudentId(testId, studentId);
        if (testAssignment == null) {
            throw new IllegalArgumentException("Test not assigned to student");
        }
        
        // Update the test assignment status to submitted
        testAssignment.setStatus("SUBMITTED");
        testAssignmentRepository.updateById(testAssignment);

        // Process each response
        for (StudentResponseDTO responseDTO : responses) {
            // Create and populate the entity
            StudentResponse response = new StudentResponse();
            // ID will be auto-generated by MyBatisPlus
            response.setTestId(testId);
            response.setStudentId(studentId);
            response.setQuestionId(responseDTO.getQuestionId());
            response.setResponseText(responseDTO.getResponseText());
            response.setSelectedOptionIndex(responseDTO.getSelectedOptionIndex());
            response.setSubmittedAt(LocalDateTime.now());

            // Insert the response
            studentResponseRepository.insert(response);

            // Also save to Elasticsearch if available
            if (studentResponseElasticsearchRepository != null) {
                try {
                    studentResponseElasticsearchRepository.save(response);
                } catch (Exception e) {
                    // Log the error but don't fail the operation
                    System.err.println("Failed to save student response to Elasticsearch: " + e.getMessage());
                }
            }
        }

        return responses;
    }

    public List<StudentResponse> getTestForStudent(Long testId, Long studentId) {
        return studentResponseRepository.findByStudentIdAndTestId(studentId, testId);
    }
    
    public Test getTestDetails(Long testId) {
        return testRepository.selectById(testId);
    }
    
    public List<StudentResponse> searchStudentResponses(String query) {
        // Search in Elasticsearch if available - searching in response text and teacher comments
        if (studentResponseElasticsearchRepository != null) {
            try {
                return studentResponseElasticsearchRepository.findByResponseTextContainingOrTeacherCommentsContaining(query, query);
            } catch (Exception e) {
                // Log the error but return empty list
                System.err.println("Failed to search student responses in Elasticsearch: " + e.getMessage());
                return java.util.Collections.emptyList();
            }
        } else {
            // Return empty list if Elasticsearch is not available
            return java.util.Collections.emptyList();
        }
    }
}