package com.exam.system.service;

import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.exam.system.dto.TestDTO;
import com.exam.system.model.Test;
import com.exam.system.repository.TestElasticsearchRepository;
import com.exam.system.repository.TestRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.stream.Collectors;

@Service
public class TestService {

    @Autowired
    private TestRepository testRepository;
    
    @Autowired
    private CacheService cacheService;
    
    @Autowired(required = false)
    private TestElasticsearchRepository testElasticsearchRepository;

    public TestDTO createTest(TestDTO testDTO) {
        // Create and populate the model
        Test test = new Test();
        // ID will be auto-generated by MyBatisPlus
        test.setTitle(testDTO.getTitle());
        test.setDescription(testDTO.getDescription());
        test.setGradeId(testDTO.getGradeId());
        test.setSubjectId(testDTO.getSubjectId());
        test.setTimeLimitMinutes(testDTO.getTimeLimitMinutes());
        test.setIsActive(testDTO.getIsActive());
        test.setIsPublished(testDTO.getIsPublished());
        test.setPublishDate(testDTO.getPublishDate());

        // Insert the model
        testRepository.insert(test);

        // Also save to Elasticsearch if available
        if (testElasticsearchRepository != null) {
            try {
                testElasticsearchRepository.save(test);
            } catch (Exception e) {
                // Log the error but don't fail the operation
                System.err.println("Failed to save test to Elasticsearch: " + e.getMessage());
            }
        }

        // Clear related cache entries
        cacheService.deletePattern("tests_*");

        // Convert back to DTO and return
        return convertToDTO(test);
    }

    public TestDTO getTestById(Long id) {
        String cacheKey = "test_" + id;
        Object cached = cacheService.get(cacheKey);
        if (cached != null) {
            return (TestDTO) cached;
        }
        
        Test test = testRepository.selectById(id);
        TestDTO result = convertToDTO(test);
        
        if (result != null) {
            cacheService.setEntity(cacheKey, result);
        }
        
        return result;
    }

    public List<TestDTO> getAllTests() {
        String cacheKey = "tests_all";
        Object cached = cacheService.get(cacheKey);
        if (cached != null) {
            return (List<TestDTO>) cached;
        }
        
        List<Test> tests = testRepository.selectList(null);
        List<TestDTO> result = tests.stream().map(this::convertToDTO).collect(Collectors.toList());
        
        cacheService.setList(cacheKey, result);
        
        return result;
    }
    
    public IPage<TestDTO> getTestsPaginated(int page, int size) {
        String cacheKey = "tests_paginated_" + page + "_" + size;
        Object cached = cacheService.get(cacheKey);
        if (cached != null) {
            return (IPage<TestDTO>) cached;
        }
        
        Page<Test> mybatisPage = new Page<>(page, size);
        IPage<Test> pageResult = testRepository.selectPage(mybatisPage, null);
        
        // Convert to DTOs
        List<TestDTO> content = pageResult.getRecords().stream()
            .map(this::convertToDTO)
            .collect(Collectors.toList());
        
        // Create a new Page object with DTOs
        Page<TestDTO> result = new Page<>();
        result.setRecords(content);
        result.setTotal(pageResult.getTotal());
        result.setSize(pageResult.getSize());
        result.setCurrent(pageResult.getCurrent());
        
        cacheService.setWithDefaultTimeout(cacheKey, result);
        
        return result;
    }

    public TestDTO updateTest(Long id, TestDTO testDTO) {
        Test existingTest = testRepository.selectById(id);
        if (existingTest != null) {
            existingTest.setTitle(testDTO.getTitle());
            existingTest.setDescription(testDTO.getDescription());
            existingTest.setGradeId(testDTO.getGradeId());
            existingTest.setSubjectId(testDTO.getSubjectId());
            existingTest.setTimeLimitMinutes(testDTO.getTimeLimitMinutes());
            existingTest.setIsActive(testDTO.getIsActive());
            existingTest.setIsPublished(testDTO.getIsPublished());
            existingTest.setPublishDate(testDTO.getPublishDate());
            
            testRepository.updateById(existingTest);
            
            // Update in Elasticsearch if available
            if (testElasticsearchRepository != null) {
                try {
                    testElasticsearchRepository.save(existingTest);
                } catch (Exception e) {
                    // Log the error but don't fail the operation
                    System.err.println("Failed to update test in Elasticsearch: " + e.getMessage());
                }
            }
            
            // Clear related cache entries
            cacheService.delete("test_" + id);
            cacheService.deletePattern("tests_*");
            
            return convertToDTO(existingTest);
        }
        return null;
    }

    public boolean deleteTest(Long id) {
        Test test = testRepository.selectById(id);
        if (test != null) {
            int result = testRepository.deleteById(id);
            
            if (result > 0) {
                // Delete from Elasticsearch if available
                if (testElasticsearchRepository != null) {
                    try {
                        testElasticsearchRepository.deleteById(id);
                    } catch (Exception e) {
                        // Log the error but don't fail the operation
                        System.err.println("Failed to delete test from Elasticsearch: " + e.getMessage());
                    }
                }
                
                // Clear related cache entries
                cacheService.delete("test_" + id);
                cacheService.deletePattern("tests_*");
                
                return true;
            }
        }
        return false;
    }

    public List<TestDTO> getTestsForStudent(Long studentId) {
        // Get tests assigned to the student via TestAssignment
        List<Test> tests = testRepository.findByStudentIdAndIsActiveTrue(studentId);
        return tests.stream().map(this::convertToDTO).collect(Collectors.toList());
    }
    
    public IPage<TestDTO> getTestsForStudentPaginated(Long studentId, int page, int size) {
        // Calculate offset for pagination
        int offset = (page - 1) * size;
        
        // Get the paginated results
        List<Test> pagedTests = testRepository.findTestsByStudentIdPaginated(studentId, offset, size);
        int totalCount = testRepository.countTestsByStudentId(studentId);
        
        // Convert to DTOs
        List<TestDTO> content = pagedTests.stream().map(this::convertToDTO).collect(Collectors.toList());
        
        // Create result page
        Page<TestDTO> result = new Page<>();
        result.setRecords(content);
        result.setTotal((long) totalCount);
        result.setSize(size);
        result.setCurrent(page);
        
        return result;
    }
    
    public List<TestDTO> searchTests(String query) {
        if (testElasticsearchRepository != null) {
            try {
                List<Test> tests = testElasticsearchRepository.findByTitleContainingOrDescriptionContaining(query, query);
                return tests.stream().map(this::convertToDTO).collect(Collectors.toList());
            } catch (Exception e) {
                // Log the error but return empty list
                System.err.println("Failed to search tests in Elasticsearch: " + e.getMessage());
                return java.util.Collections.emptyList();
            }
        } else {
            // Return empty list if Elasticsearch is not available
            return java.util.Collections.emptyList();
        }
    }

    private TestDTO convertToDTO(Test test) {
        if (test == null) {
            return null;
        }
        
        TestDTO dto = new TestDTO();
        dto.setId(test.getId());
        dto.setTitle(test.getTitle());
        dto.setDescription(test.getDescription());
        dto.setGradeId(test.getGradeId());
        dto.setSubjectId(test.getSubjectId());
        dto.setTimeLimitMinutes(test.getTimeLimitMinutes());
        dto.setIsActive(test.getIsActive());
        dto.setIsPublished(test.getIsPublished());
        dto.setPublishDate(test.getPublishDate());
        
        return dto;
    }
}