-- 004 exam workflow core chain migration
CREATE TABLE IF NOT EXISTS exam_papers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    subject_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    blueprint CLOB,
    status VARCHAR(32) DEFAULT 'DRAFT',
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (subject_id) REFERENCES subjects(id),
    FOREIGN KEY (class_id) REFERENCES classes(id)
);

CREATE TABLE IF NOT EXISTS exam_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paper_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    status VARCHAR(32) DEFAULT 'SCHEDULED',
    published_at TIMESTAMP,
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (paper_id) REFERENCES exam_papers(id),
    FOREIGN KEY (class_id) REFERENCES classes(id),
    FOREIGN KEY (subject_id) REFERENCES subjects(id)
);

CREATE TABLE IF NOT EXISTS exam_invigilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_session_id BIGINT NOT NULL,
    teacher_id VARCHAR(36) NOT NULL,
    status VARCHAR(32) DEFAULT 'IN_PROGRESS',
    started_at TIMESTAMP,
    ended_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (exam_session_id) REFERENCES exam_sessions(id),
    FOREIGN KEY (teacher_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS exam_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_session_id BIGINT NOT NULL,
    student_id VARCHAR(36) NOT NULL,
    answers CLOB,
    score DECIMAL(5,2),
    status VARCHAR(32) DEFAULT 'SUBMITTED',
    graded_by VARCHAR(36),
    submitted_at TIMESTAMP,
    graded_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (exam_session_id) REFERENCES exam_sessions(id),
    FOREIGN KEY (student_id) REFERENCES users(id),
    FOREIGN KEY (graded_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS exam_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_session_id BIGINT NOT NULL,
    avg_score DECIMAL(6,2),
    pass_rate DECIMAL(5,2),
    excellent_rate DECIMAL(5,2),
    warning_count INT DEFAULT 0,
    recommendation VARCHAR(1000),
    generated_at TIMESTAMP,
    FOREIGN KEY (exam_session_id) REFERENCES exam_sessions(id)
);

CREATE INDEX IF NOT EXISTS idx_exam_papers_subject ON exam_papers(subject_id);
CREATE INDEX IF NOT EXISTS idx_exam_sessions_paper ON exam_sessions(paper_id);
CREATE INDEX IF NOT EXISTS idx_exam_invigilations_session ON exam_invigilations(exam_session_id);
CREATE INDEX IF NOT EXISTS idx_exam_submissions_session ON exam_submissions(exam_session_id);
CREATE INDEX IF NOT EXISTS idx_exam_submissions_student ON exam_submissions(student_id);
CREATE INDEX IF NOT EXISTS idx_exam_analyses_session ON exam_analyses(exam_session_id);
