-- Knowledge Points and Questions Management Module schema

-- Create knowledge_points table
CREATE TABLE IF NOT EXISTS knowledge_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(50) UNIQUE NOT NULL,
    parent_id BIGINT DEFAULT NULL,
    subject_id BIGINT DEFAULT NULL,
    description VARCHAR(500) DEFAULT NULL,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_knowledge_point_subject FOREIGN KEY (subject_id) REFERENCES subjects(id)
);

-- Create questions table
CREATE TABLE IF NOT EXISTS questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    type VARCHAR(20) NOT NULL,
    difficulty VARCHAR(20) DEFAULT NULL,
    score INT DEFAULT NULL,
    answer TEXT COMMENT '答案',
    analysis TEXT COMMENT '解析',
    subject_id BIGINT DEFAULT NULL,
    grade_id BIGINT DEFAULT NULL,
    knowledge_point_id BIGINT DEFAULT NULL,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    created_by VARCHAR(64),
    updated_by VARCHAR(64),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_question_subject FOREIGN KEY (subject_id) REFERENCES subjects(id),
    CONSTRAINT fk_question_grade FOREIGN KEY (grade_id) REFERENCES grades(id),
    CONSTRAINT fk_question_knowledge_point FOREIGN KEY (knowledge_point_id) REFERENCES knowledge_points(id)
);

-- Modify exam_papers table to add grade_id
ALTER TABLE exam_papers ADD COLUMN grade_id BIGINT DEFAULT NULL,
ADD CONSTRAINT fk_exam_paper_grade FOREIGN KEY (grade_id) REFERENCES grades(id);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_knowledge_points_parent_id ON knowledge_points(parent_id);
CREATE INDEX IF NOT EXISTS idx_knowledge_points_subject_id ON knowledge_points(subject_id);
CREATE INDEX IF NOT EXISTS idx_questions_subject_id ON questions(subject_id);
CREATE INDEX IF NOT EXISTS idx_questions_grade_id ON questions(grade_id);
CREATE INDEX IF NOT EXISTS idx_questions_knowledge_point_id ON questions(knowledge_point_id);
CREATE INDEX IF NOT EXISTS idx_exam_papers_grade_id ON exam_papers(grade_id);

-- Insert sample data for knowledge points
MERGE INTO knowledge_points (id, name, code, parent_id, subject_id, status) KEY(id) VALUES
(1, '数学基础', 'MATH_BASIC', NULL, 1, 'ACTIVE'),
(2, '加减法', 'MATH_ADD_SUB', 1, 1, 'ACTIVE'),
(3, '乘除法', 'MATH_MUL_DIV', 1, 1, 'ACTIVE'),
(4, '语文基础', 'CHINESE_BASIC', NULL, 2, 'ACTIVE'),
(5, '拼音', 'CHINESE_PINYIN', 4, 2, 'ACTIVE');

-- Insert sample data for questions
MERGE INTO questions (id, content, type, difficulty, score, answer, analysis, subject_id, grade_id, knowledge_point_id, status) KEY(id) VALUES
(1, '1+1=?', '选择题', 'EASY', 5, '2', '1+1=2', 1, 1, 2, 'ACTIVE'),
(2, '2+3=?', '选择题', 'EASY', 5, '5', '2+3=5', 1, 1, 2, 'ACTIVE'),
(3, '3×4=?', '选择题', 'MEDIUM', 10, '12', '3×4=12', 1, 2, 3, 'ACTIVE');

-- Update exam_papers to add grade_id
UPDATE exam_papers SET grade_id = 1 WHERE id = 1;